volumes:
  strapi-db-data: {}
  strapi-upload-data: {}
  chroma-db-data: {}

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    environment:
      NODE_ENV: production
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped
    depends_on:
      - strapi
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "127.0.0.1:8000:8000"
    restart: unless-stopped
    depends_on:
      - chroma

  chroma:
    image: ghcr.io/chroma-core/chroma:0.6.3
    container_name: chroma_db
    restart: unless-stopped
    volumes:
      - chroma-db-data:/data

  strapi:
    container_name: strapi
    build:
      context: ./cms
      dockerfile: .Dockerfile
    image: strapi:latest
    restart: unless-stopped
    env_file: .env-compose
    volumes:
      - strapi-upload-data:/app/public/uploads
    ports:
      - "127.0.0.1:1337:1337"
    depends_on:
      - strapiDB

  strapiDB:
    image: postgres:15
    container_name: strapiDB
    restart: unless-stopped
    env_file: .env-compose
    volumes:
      - strapi-db-data:/var/lib/postgresql/data